name: "dbt_fullstory"
version: "0.9.3"
config-version: 2
require-dbt-version: [">=1.6.0", "<2.0.0"]

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_fullstory"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  dbt_fullstory:
    # Materializations for "final", top-level semantic models are controlled via a config block in the sql files themselves.
    # The models in the /models folder are intended for use in databases and/or consumption in other dbt packages.
    # See https://docs.getdbt.com/docs/build/incremental-models for more details.

    +materialized: view
    +incremental_strategy: merge
    +on_schema_change: fail

    sessions:
      +materialized: incremental

    # These materializations are for the protected, intermediate and staging models; they are not intended for direct querying
    # or use in other dbt packages.
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral


  +persist_docs:
    columns: true
    relation: true

vars:
  dbt_date:time_zone: Etc/UTC
  fullstory_incremental_interval_hours: 192 # 8 days
  fullstory_replay_host: app.fullstory.com

  # For filtering all event data, if necessary
  fullstory_min_event_time: "1900-01-01 00:00:00" # Inclusive

  fullstory_events_types:
    [
      "background",
      "change",
      "click",
      "consent",
      "console_message",
      "copy",
      "crash",
      "cumulative_layout_shift",
      "custom",
      "element_seen",
      "exception",
      "first_input_delay",
      "form_abandon",
      "highlight",
      "identify",
      "keyboard_close",
      "keyboard_open",
      "load",
      "low_memory",
      "mouse_thrash",
      "navigate",
      "page_properties",
      "paste",
      "pinch_gesture",
      "request",
    ]
