config:
  send_anonymous_usage_stats: False
  use_colors: True

dbt_fullstory_integration_tests:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('BIGQUERY_SERVICE_KEY_PATH') }}"
      project: "{{ env_var('BIGQUERY_GCP_PROJECT') }}"
      dataset: "dbt_fullstory_testing"
      threads: 4
      priority: interactive

    bigquery_v2:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('BIGQUERY_SERVICE_KEY_PATH') }}"
      project: "{{ env_var('BIGQUERY_GCP_PROJECT') }}"
      dataset: "dbt_fullstory_testing_v2"
      threads: 4
      priority: interactive

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_TEST_USER') }}"
      password: "{{ env_var('SNOWFLAKE_TEST_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_TEST_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_TEST_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TEST_WAREHOUSE') }}"
      schema: dbt_fullstory_testing
      threads: 4

    redshift:
      type: redshift
      host: "{{ env_var('REDSHIFT_URL') }}"
      port: 5439
      method: iam
      user: serverlessuser
      iam_profile: default
      dbname: dev
      schema: dbt_fullstory_integration_tests
      region: "{{ env_var('REDSHIFT_REGION') }}"
      threads: 4
      connect_timeout: 30
