select
  e.event_id,
  e.device_id,
  e.session_id,
  e.full_session_id,
  e.view_id,
  e.event_time,
  e.updated_time,
  e.processed_time,
  e.device_user_agent,
  e.device_type,
  e.device_operating_system,
  e.device_browser,
  e.device_browser_version,
  e.geo_ip_address,
  e.geo_country,
  e.geo_region,
  e.geo_city,
  e.geo_lat_long,
  e.url_full_url,
  e.url_host,
  e.url_path,
  e.url_query,
  e.url_hash_path,
  e.url_hash_query,
  e.initial_referrer_full_url,
  e.initial_referrer_host,
  e.initial_referrer_path,
  e.initial_referrer_query,
  e.initial_referrer_hash_path,
  e.initial_referrer_hash_query,
  p.id as page_id,
  p.name as page_name,
  p.description as page_description,
  p.is_user_defined as page_is_user_defined,
  p.state as page_state
from {{ ref('int_pageviews')}} e
left join {{ ref('stg_page_definitions__all') }} p on e.page_definition_id = p.id