models:
  - name: anonymous_users
    access: public
    config:
      alias: "{{ var('fullstory_anonymous_users_model_name', 'anonymous_users') }}"
      contract:
        enforce: true
    description: |-
      All users who have never been identified.
    columns:
      - name: device_id
        description: '{{ doc("column_last_device_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: last_device_user_agent
        description: '{{ doc("column_last_device_user_agent") }}'
      - name: last_device_type
        description: '{{ doc("column_last_device_type") }}'
      - name: last_device_operating_system
        description: '{{ doc("column_last_device_operating_system") }}'
      - name: last_device_browser
        description: '{{ doc("column_last_device_browser") }}'
      - name: last_device_browser_version
        description: '{{ doc("column_last_device_browser_version") }}'
      - name: last_geo_ip_address
        description: '{{ doc("column_last_geo_ip_address") }}'
      - name: last_geo_country
        description: '{{ doc("column_last_geo_country") }}'
      - name: last_geo_region
        description: '{{ doc("column_last_geo_region") }}'
      - name: last_geo_city
        description: '{{ doc("column_last_geo_city") }}'
      - name: last_geo_lat_long
        description: '{{ doc("column_last_geo_lat_long") }}'
      - name: last_event_time
        description: '{{ doc("column_last_event_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: last_event_id
        description: '{{ doc("column_last_event_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
  - name: devices
    access: public
    config:
      alias: "{{ var('fullstory_devices_model_name', 'devices') }}"
      contract:
        enforce: true
    description: |-
      All events that have device information. The latest data for a device is located where `event_seq_num_desc` = 1.
    columns:
      - name: event_id
        description: '{{ doc("column_event_id") }}'
        constraints:
          - type: primary_key
          - type: not_null
        tests:
          - not_null
          - unique
      - name: id
        description: '{{ doc("column_device_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: event_time
        description: '{{ doc("column_event_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: updated_time
        description: '{{ doc("column_updated_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: processed_time
        description: '{{ doc("column_processed_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: user_agent
        description: '{{ doc("column_device_user_agent") }}'
      - name: type
        description: '{{ doc("column_device_type") }}'
      - name: operating_system
        description: '{{ doc("column_device_operating_system") }}'
      - name: browser
        description: '{{ doc("column_device_browser") }}'
      - name: browser_version
        description: '{{ doc("column_device_browser_version") }}'
      - name: geo_ip_address
        description: '{{ doc("column_geo_ip_address") }}'
      - name: geo_country
        description: '{{ doc("column_geo_country") }}'
      - name: geo_region
        description: '{{ doc("column_geo_region") }}'
      - name: geo_city
        description: '{{ doc("column_geo_city") }}'
      - name: geo_lat_long
        description: '{{ doc("column_geo_lat_long") }}'
      - name: source_type
        description: '{{ doc("column_source_type") }}'
      - name: event_seq_num_desc
        description: '{{ doc("column_event_seq_num_desc") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
  - name: events
    access: public
    config:
      alias: "{{ var('fullstory_events_model_name', 'events') }}"
      contract:
        enforce: true
    description: |-
      All events emitted by Fullstory.
    columns:
      - name: event_id
        description: '{{ doc("column_event_id") }}'
        constraints:
          - type: primary_key
          - type: not_null
        tests:
          - not_null
          - unique
      - name: device_id
        description: '{{ doc("column_device_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: session_id
        description: '{{ doc("column_session_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: view_id
        description: '{{ doc("column_view_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: event_time
        description: '{{ doc("column_event_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: event_type
        description: '{{ doc("column_event_type") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: element_definition_id
        description: '{{ doc("column_element_definition_id") }}'
      - name: additional_element_definition_ids
        description: '{{ doc("column_additional_element_definition_ids") }}'
      - name: source_type
        description: '{{ doc("column_source_type") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: updated_time
        description: '{{ doc("column_updated_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: processed_time
        description: '{{ doc("column_processed_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: full_session_id
        description: '{{ doc("column_full_session_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: device_user_agent
        description: '{{ doc("column_device_user_agent") }}'
      - name: device_type
        description: '{{ doc("column_device_type") }}'
      - name: device_operating_system
        description: '{{ doc("column_device_operating_system") }}'
      - name: device_browser
        description: '{{ doc("column_device_browser") }}'
      - name: device_browser_version
        description: '{{ doc("column_device_browser_version") }}'
      - name: geo_ip_address
        description: '{{ doc("column_geo_ip_address") }}'
      - name: geo_country
        description: '{{ doc("column_geo_country") }}'
      - name: geo_region
        description: '{{ doc("column_geo_region") }}'
      - name: geo_city
        description: '{{ doc("column_geo_city") }}'
      - name: geo_lat_long
        description: '{{ doc("column_geo_lat_long") }}'
      - name: url_full_url
        description: '{{ doc("column_url_full_url") }}'
      - name: url_host
        description: '{{ doc("column_url_host") }}'
      - name: url_path
        description: '{{ doc("column_url_path") }}'
      - name: url_query
        description: '{{ doc("column_url_query") }}'
      - name: url_hash_path
        description: '{{ doc("column_url_hash_path") }}'
      - name: url_hash_query
        description: '{{ doc("column_url_hash_query") }}'
      - name: initial_referrer_full_url
        description: '{{ doc("column_initial_referrer_full_url") }}'
      - name: initial_referrer_host
        description: '{{ doc("column_initial_referrer_host") }}'
      - name: initial_referrer_path
        description: '{{ doc("column_initial_referrer_path") }}'
      - name: initial_referrer_query
        description: '{{ doc("column_initial_referrer_query") }}'
      - name: initial_referrer_hash_path
        description: '{{ doc("column_initial_referrer_hash_path") }}'
      - name: initial_referrer_hash_query
        description: '{{ doc("column_initial_referrer_hash_query") }}'
      - name: event_properties
        description: '{{ doc("column_event_properties") }}'
      - name: source_properties
        description: '{{ doc("column_source_properties") }}'
      - name: target_masked
        description: '{{ doc("column_target_masked") }}'
      - name: target_raw_selector
        description: '{{ doc("column_target_raw_selector") }}'
      - name: target_element_properties
        description: '{{ doc("column_target_element_properties") }}'
      - name: target_text
        description: '{{ doc("column_target_text") }}'
      - name: user_display_name
        description: '{{ doc("column_user_display_name") }}'
      - name: user_email
        description: '{{ doc("column_user_email") }}'
      - name: user_id
        description: '{{ doc("column_user_id") }}'
      - name: user_properties
        description: '{{ doc("column_user_properties") }}'
  - name: identified_users
    access: public
    config:
      alias: "{{ var('fullstory_identified_users_model_name', 'identified_users') }}"
      contract:
        enforce: true
    description: |-
      All users who have been identified.
    columns:
      - name: user_id
        description: '{{ doc("column_user_id") }}'
        constraints:
          - type: primary_key
          - type: not_null
        tests:
          - not_null
          - unique
      - name: user_email
        description: '{{ doc("column_user_email") }}'
      - name: user_display_name
        description: '{{ doc("column_user_display_name") }}'
      - name: user_properties
        description: '{{ doc("column_user_properties") }}'
      - name: last_device_id
        description: '{{ doc("column_last_device_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: last_device_user_agent
        description: '{{ doc("column_last_device_user_agent") }}'
      - name: last_device_type
        description: '{{ doc("column_last_device_type") }}'
      - name: last_device_operating_system
        description: '{{ doc("column_last_device_operating_system") }}'
      - name: last_device_browser
        description: '{{ doc("column_last_device_browser") }}'
      - name: last_device_browser_version
        description: '{{ doc("column_last_device_browser_version") }}'
      - name: last_geo_ip_address
        description: '{{ doc("column_last_geo_ip_address") }}'
      - name: last_geo_country
        description: '{{ doc("column_last_geo_country") }}'
      - name: last_geo_region
        description: '{{ doc("column_last_geo_region") }}'
      - name: last_geo_city
        description: '{{ doc("column_last_geo_city") }}'
      - name: last_geo_lat_long
        description: '{{ doc("column_last_geo_lat_long") }}'
      - name: last_event_time
        description: '{{ doc("column_last_event_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: last_event_id
        description: '{{ doc("column_last_event_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: last_updated_time
        description: '{{ doc("column_last_updated_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: last_processed_time
        description: '{{ doc("column_last_processed_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
  - name: identifies
    access: public
    config:
      alias: "{{ var('fullstory_identifies_model_name', 'identifies') }}"
      contract:
        enforce: true
    description: |-
      All identify events tracked from the FS SDKs or API.
    columns:
      - name: event_id
        description: '{{ doc("column_event_id") }}'
        constraints:
          - type: primary_key
          - type: not_null
        tests:
          - not_null
          - unique
      - name: device_id
        description: '{{ doc("column_device_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: session_id
        description: '{{ doc("column_session_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: view_id
        description: '{{ doc("column_view_id") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: event_time
        description: '{{ doc("column_event_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: updated_time
        description: '{{ doc("column_updated_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: processed_time
        description: '{{ doc("column_processed_time") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: source_type
        description: '{{ doc("column_source_type") }}'
      - name: user_id
        description: '{{ doc("column_user_id") }}'
      - name: user_email
        description: '{{ doc("column_user_email") }}'
      - name: user_display_name
        description: '{{ doc("column_user_display_name") }}'
      - name: user_properties
        description: '{{ doc("column_user_properties") }}'
      - name: event_seq_num_desc
        description: '{{ doc("column_event_seq_num_desc") }}'
        constraints:
          - type: not_null
        tests:
          - not_null
